/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IxButton: typeof import('@idux/components/button')['IxButton']
    IxCheckbox: typeof import('@idux/components/checkbox')['IxCheckbox']
    IxCol: typeof import('@idux/components/grid')['IxCol']
    IxForm: typeof import('@idux/components/form')['IxForm']
    IxFormItem: typeof import('@idux/components/form')['IxFormItem']
    IxIcon: typeof import('@idux/components/icon')['IxIcon']
    IxInput: typeof import('@idux/components/input')['IxInput']
    IxRow: typeof import('@idux/components/grid')['IxRow']
    IxSpace: typeof import('@idux/components/space')['IxSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
